services:
  gowheels:
    image: ${DOCKER_USERNAME}/gowheels:${LATEST_TAG}
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "4054:4054"
    environment:
      - PORT=4054
    env_file:
      - .env
