version: '3.8'

services:
  gowheels:
    image: wheelsimg
    container_name: wheelc
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "4054:4054"
    env_file:
      - .env.production
    networks:
      - my_ipv6_network

networks:
  my_ipv6_network:
    external: true